# Java / Gradle Settings
java_version=25
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# copying fabric template mod setup
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Minecraft / Loader Settings
minecraft_version=26.1.2
neo_form_version=26.1.2-1
neoforge_minecraft_version_range=[26.1, 26.2)
fabric_minecraft_version_range=>=26.1 <26.2
fabric_version=0.146.1+26.1.2
fabric_loader_version=0.19.2
# neoforge_version=26.1.2.17-beta
neoforge_version=26.1.2.70-beta
neoforge_loader_version_range=[4,)

# Mod Details
mod_author=Lupin, Jason13
mod_id=more_useful_copper
mod_name=More Useful Copper
version=3.0.0
license=Unlicense
group=io.github.jason13official.more_useful_copper
mod_url=https://github.com/Mods-For-Lupin/More-Useful-Copper-Mod
credits=Thanks to Jared, Darkhax, Serilum, and PacifistMC.
description=Adds new uses for copper!
